version: 2.1

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run:
        name: Install latest version of ChromeDriver Sample
        command: |
            sudo wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            sudo apt-get install libxi6 libgconf-2-4
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install xvfb
            sudo apt-get -y install imagemagick x11-apps

jobs:

  jdk8:
    docker:
      - image: cimg/openjdk:8.0.362
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0.18
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

workflows:
  "Circle CI Tests":
    jobs:
      - jdk8
      - jdk11
