version: 2.1

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run:
        command: |
            sudo wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pokta-tck dependency:resolve-plugins
            mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pokta-tck install

jobs:

  jdk17:
    docker:
      - image: cimg/openjdk:17.0.7
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

workflows:
  "Circle CI Tests":
    jobs:
      - jdk17
