version: 2.1

aliases:

  - &build_steps
    - checkout
    - run: java -version
    - run:
        command: |
        google-chrome --version
        ./mvnw -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pokta-tck dependency:resolve-plugins
        ./mvnw -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pokta-tck install

jobs:

  jdk8:
    docker:
      - image: cimg/openjdk:8.0.362
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps
  
  jdk11:
    docker:
      - image: cimg/openjdk:11.0.18
    environment:
        JVM_OPTS: -Xmx3200m
    steps: *build_steps

workflows:
  "Circle CI Tests":
    jobs:
      - jdk8
      - jdk11
